# Header
menu:
  主页: /
  分类: /categories
  标签: /tags
  归档: /archives
  关于: /about
rss: /atom.xml

home:
  style: default           # default, detail

favicon: assets/avatar.png # Path to the custom favicon (e.g. "/favicon.png" if your favicon file is located at /source/favicon.png)

# Banner
banner:
  enable: true             # Display banner
  url: assets/banner.png
  position: center         # Specifies the alignment of the image, see the "object-position" property in CSS
  onAllPages: true         # Display banner on all pages

# Appearence
hue: 250                   # The hue of the theme color (e.g. red: 0, orange: 60, blue: 260, purple: 300, pink: 345)

# Sidebar
sidebar:
  widgets:                 # Plugins to be enabled (profile, category, tag, archive, recent_posts)
    normal:                # Scroll along with the page
      - profile
    sticky:                # Stick to the top of the page
      - category
      - tag
      - archive
      - recent_posts

# Widget behavior
archive_type: 'monthly'
recent_posts_limits: 5
categories:
  max_depth:              # Maximum depth of categories displayed in the widget (null for unlimited)

# Personal info
avatar: assets/avatar.png
author: Juvwxyz
subtitle: Juvwxyz的个人博客
links:
  - name: QQ频道
    icon: fa-brands fa-qq
    url: https://pd.qq.com/s/l6or31f5
  - name: bilibili
    icon: fa-brands fa-bilibili
    url: https://space.bilibili.com/6512552
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com/Juvwxyz

comment:
  valine:
    enable: true
    appId: ArZDJY9XiAQL6bsZRCpAiOpa-gzGzoHsz
    appKey: Yn9b3iymFfSJYdAIAj9FXeA8
    placeholder: Just go go
    pageSize: 10
    highlight: true
    serverURLs: https://arzdjy9x.lc-cn-n1-shared.com
    # Other supported parameters can be added here if needed
    # Visit https://valine.js.org/configuration.html for more details


#Analytics
gauges_analytics: false
google_analytics: false #UA-xxxxxx
baidu_analytics: false # ddxxxxxxxxxxxxxxxxx In the https://hm.baidu.com/hm.js? Afterwards

#Copyright
copyright: #<a target="_blank" rel="noopener" href="http://creativecommons.org/licenses/by-nc-sa/4.0/" style="margin-inline:5px" title="本站采用知识共享署名-非商业性使用-相同方式共享4.0国际许可协议进行许可"><img src="https://img.shields.io/badge/Copyright-BY--NC--SA%204.0-d42328?style=flat&amp;logo=Claris"></a>